version: '3'
services:
  myapp:
    build: .
    networks:
      - frontend
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    networks:
      - frontend
networks:
  frontend:      
